// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANfvjX4XYbUWLpcjyv7oAlK7mJIO3Ocl4',
    appId: '1:724013755773:web:63dc98b63f71e23a77b014',
    messagingSenderId: '724013755773',
    projectId: 'handychat-2bdd0',
    authDomain: 'handychat-2bdd0.firebaseapp.com',
    storageBucket: 'handychat-2bdd0.firebasestorage.app',
    measurementId: 'G-5LDBZ9P9C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO66wiTUpllyM-0khv_k-BOrLjsMPD7Xw',
    appId: '1:724013755773:android:2402cafeddf463ea77b014',
    messagingSenderId: '724013755773',
    projectId: 'handychat-2bdd0',
    storageBucket: 'handychat-2bdd0.firebasestorage.app',
  );
}
