// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2z3aL1p9H9djkNkAf_w7g5yIkSvzrFGU',
    appId: '1:979449960272:web:adb386d0bbae7b108dbe55',
    messagingSenderId: '979449960272',
    projectId: 'handychat-6c954',
    authDomain: 'handychat-6c954.firebaseapp.com',
    storageBucket: 'handychat-6c954.firebasestorage.app',
    measurementId: 'G-L61YF73JLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuX_oX1dY-GEhxiNNlo6q_SxTW6QMAjI',
    appId: '1:979449960272:android:92336d57a5c9373f8dbe55',
    messagingSenderId: '979449960272',
    projectId: 'handychat-6c954',
    storageBucket: 'handychat-6c954.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbEaj6c7RicVdHeU_XZYtD1hosOvy8Q8I',
    appId: '1:979449960272:ios:1d407ffd3ad410b08dbe55',
    messagingSenderId: '979449960272',
    projectId: 'handychat-6c954',
    storageBucket: 'handychat-6c954.firebasestorage.app',
    iosBundleId: 'com.example.handychat',
  );
}
